### ISSUE TITLE
DateSelect form elements do not work with DoctrineORM (AnnotationBuilder/Hydrator)

### ISSUE THREAD

**Issue by internalsystemerror** [doctrine/DoctrineORMModule#515] opened 2016-12-26 16:37 UTC
I've spent a long time trying to track down the exact reasons for this, and to implement a possible solution. I'm not entirely sure that it's limited only to the AnnotationBuilder, it could just be an issue for the Hydrator.

This issue first came for me when I was trying to implement my own Zend\Form\Element type to correspond to a custom Doctrine\DBAL\Type. This was essentially 2 fields, concatenated to a string, however the raw array value was passed to the entity and not the filtered string.

I've come to the conclusion that this is related to the base issue of the DateSelect, DateTimeSelect, MonthSelect not working with the DoctrineORM hydrator.

I've set up the following Test Application (ZF 2.5, DoctrineORMModule 1.1 + Test Entity + Form) https://github.com/internalsystemerror/zf2-testapp-doctrineormmodule to assist in diagnosis.

Either my approach is wrong, I've misunderstood something, or there is a bug here that extends beyond the simple DateSelect elements, but would apply to any other custom elements implementing the same approach.

File: ```module\Application\src\Entity\Test.php:37```
Message: ```Argument 1 passed to Application\Entity\Test::setTestDate() must be an instance of DateTime or null, array given, called in vendor\doctrine\doctrine-module\src\DoctrineModule\Stdlib\Hydrator\DoctrineObject.php on line 282```
        
Stack trace (all paths are relative to project root):
```
0. vendor\doctrine\doctrine-module\src\DoctrineModule\Stdlib\Hydrator\DoctrineObject.php(282): Application\Entity\Test->setTestDate(Array)
1. vendor\doctrine\doctrine-module\src\DoctrineModule\Stdlib\Hydrator\DoctrineObject.php(105): DoctrineModule\Stdlib\Hydrator\DoctrineObject->hydrateByValue(Array, Object(Application\Entity\Test))
2. vendor\zendframework\zend-form\src\Fieldset.php(600): DoctrineModule\Stdlib\Hydrator\DoctrineObject->hydrate(Array, Object(Application\Entity\Test))
3. vendor\zendframework\zend-form\src\Form.php(367): Zend\Form\Fieldset->bindValues(Array, NULL)
4. vendor\zendframework\zend-form\src\Form.php(517): Zend\Form\Form->bindValues()
5. module\Application\src\Controller\IndexController.php(82): Zend\Form\Form->isValid()
6. module\Application\src\Controller\IndexController.php(57): Application\Controller\IndexController->addNewTest(Array)
7. vendor\zendframework\zend-mvc\src\Controller\AbstractActionController.php(82): Application\Controller\IndexController->indexAction()
8. [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
9. vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
10. vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
11. vendor\zendframework\zend-mvc\src\Controller\AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
12. vendor\zendframework\zend-mvc\src\DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
13. [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
14. vendor\zendframework\zend-eventmanager\src\EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
15. vendor\zendframework\zend-eventmanager\src\EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
16. vendor\zendframework\zend-mvc\src\Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
17. public\index.php(13): Zend\Mvc\Application->run()
```

**Comment by Ocramius** [comment] 2016-12-26 16:39
> I've set up the following Test Application (ZF 2.5, DoctrineORMModule 1.1 + Test Entity + Form) https://github.com/internalsystemerror/zf2-testapp-doctrineormmodule to assist in diagnosis.

A test case is needed, sorry :-(

**Comment by internalsystemerror** [comment] 2016-12-26 16:43
I figured that would be necessary, I'm currently looking into it as a PR.

**Comment by internalsystemerror** [comment] 2016-12-26 18:16
@Ocramius As per the test, I'm unsure where exactly I should be putting this (DoctrineModule or DoctrineORMModule) as it would be involving both the Hydrator and the AnnotationBuilder, each separately works as intended I suspect. The result of creating a form containing a DateSelect element results in an array being passed to the Hydrator to be converted to a DateTime element.

In short, should the Hydrator be made to convert an array into a DateTime element, or is another way possible.

With regards to the PR, if the test is appropriate, then I will also commit a test for DateTimeSelect.

**Comment by Ocramius** [comment] 2016-12-28 01:42
I would first try putting together a test for `DoctrineORMModule` only: we can migrate it once the issue is clear here, and also if the responsibility of `DateTime` conversions is up to this package (seems more of a filter concern to me, though)

**Comment by Ocramius** [comment] 2016-12-28 01:43
Note that `DoctrineModule` and `DoctrineORMModule` don't convert the given data: the hydrator just stuffs an object with data and eventually associations, but the given scalar values must already be in their respective format (converted by a `Zend\InputFilter`, usually)

**Comment by internalsystemerror** [comment] 2016-12-28 15:23
Thats confirms my initial investigation. My thoughts were around passing an array of elements to the hydrator, calling $element->getValue() would return a DateTime string which the Hydrator can already parse correctly.

What I'm currently stuck on, is why the values being passed to the hydrator are unfiltered. It seems this is due to the form using the hydrator to hydrate the entity, and it is the entity on which the validations are then performed. Personally I would want the entity to be hydrated only with the filtered + validated values, but this I suspect would be a design change.

If there is a solution to get the DateSelect/DateTimeSelect elements (they are considered by ZF to be elements and not fieldsets) working in DoctrineORM, then I would only ask that custom elements be able to follow this same approach. Any ideas you have on this, I'm all ears. I'm happy to implement the solution to submit as a PR, just unsure on what it should be (what the intentions are).

**Comment by mpalourdio** [comment] 2016-12-28 19:08
You can take a look of what I had done to handle date conversions with this module: https://github.com/mpalourdio/MpaCustomDoctrineHydrator

The purpose was to provide automatic hydration strategy for some ZF2 date form elements regarding locale formats.

Not sure if this works correctly again today with last releases, but it's a good start IMO if you want to handle such cases.

**Comment by Ocramius** [comment] 2016-12-29 04:05
As per pointers given by @mpalourdio, closing here.

Indeed, filtering happens before hydration, and is a separate domain.

**Closed by Ocramius** 2016-12-29 04:05 UTC
Labels: question

**Comment by internalsystemerror** [comment] 2016-12-29 04:44
Just to be clear. There is no intention for DoctrineORMModule to support all Zend\Form element types?

**Comment by Ocramius** [comment] 2016-12-29 04:46
No, and types are also kept very generic at ORM layer too (no assumptions
about types done there)

**Comment by internalsystemerror** [comment] 2016-12-29 04:46
@ocramius thank you, I'll implement a custom hydrator in my own project to handle such cases
