### ISSUE TITLE
Connect To Oracle By Symfony 4

### ISSUE THREAD

**Issue by falahatiali** [doctrine/DoctrineORMModule#575] opened 2018-08-12 11:54 UTC
Hello Everyone
I wanna Connect to Oracle Database into Symfony 4 Framework.
How can I this action by Doctrine ? 
is it Impossible that we Create Table And Database through migration ?

**Comment by Ocramius** [comment] 2018-08-13 09:30
Closing here, since this is not a bug. Connection parameters for OCI8 can be found in the `doctrine/dbal` documentation.

**Closed by Ocramius** 2018-08-13 09:30 UTC
