### ISSUE TITLE
Lazy connection with command line

### ISSUE THREAD

**Issue by coolmic** [doctrine/DoctrineORMModule#383] opened 2015-02-19 11:25 UTC
When I use command line, but didn't configure connection credentials, I get an error

With only :
```
php public/index.php
```

I get : 
```
Warning: array_map(): An error occurred while invoking the map callback in /private/var/www/website/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 138
```

The main reason is because 
```
Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES)
``` 

It's easy to fix, but I planned to use zf2 command line to configure doctrine connection on testing/production server. 

I would understand if I got this error when trying to use orm or migrations tools. But DoctrineOrmModule will try to connect to database even when I don't use database manipulation commands.

Would be great if database connection occur only when using DoctrineOrmModule command lines.

**Comment by Thinkscape** [comment] 2015-03-10 14:50
I second that. It seems that `DoctrineORMModule\Module::initializeConsole()` is forcing a db connection, but it shouldn't.

This also breaks ZendDiagnostics - i.e. it's impossible to write a diagnostics check for db connection, because diagnostics **never run** due to unhandled exception at `Zend\Application::boostrap()`.

**Comment by Thinkscape** [comment] 2015-03-10 14:52
ps: here's the full stack https://gist.github.com/Thinkscape/4a414653a7945d315f36

**Comment by Thinkscape** [comment] 2015-03-10 15:01
@coolmic It's caused by platform auto-detection. You can work around it by providing platform in connection config, or for mysql, providing server version, i.e.: 
````php
<?php return [
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params'      => [
                    'host'     => '10.0.10.1',
                    'user'     => 'root',
                    'password' => '',
                    'dbname'   => 'db',
                    'serverVersion' => '5.5.2'                   // <---- ADD THIS
                ]
            ],
        ],
    ],
];
````

**Comment by coolmic** [comment] 2015-03-11 14:07
It's not a very good workaround. 

I develop the app, but I am not the one who deploy on test or production server. 
I wanted to create a setup with the cli, to configure all local settings, to allow the administrator to install all easily.
Instead of asking administrator to copy paste all *.local.php.dist to *.local.php.dist, and editing theses files.

**Comment by gianarb** [comment] 2015-04-09 10:41
I close this issue.
If you are other question about this argument I reopen.

Thanks

**Closed by gianarb** 2015-04-09 10:41 UTC
Labels: question
