### ISSUE TITLE
Doctrine orm module error when installing on ZF3

### ISSUE THREAD

**Issue by gulijiyag** [doctrine/DoctrineORMModule#491] opened 2016-07-20 10:41 UTC
It seems that Zend Skeleton (I tried to install using [this tutorial](https://docs.zendframework.com/tutorials/getting-started/skeleton-application/)) updated and now it comes with zend-mvc version 3.0.1, but when I try to install DoctrineORMModule, I get this error:

Using version ^1.0 for doctrine/doctrine-orm-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-orm-module ^1.0 -> satisfiable by doctrine/doctrine-orm-module[1.0.0].
    - doctrine/doctrine-orm-module 1.0.0 requires zendframework/zend-mvc ^2.5.2 -> satisfiable by zendframework/zend-mvc[2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.1, 2.7.10, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by narekps** [comment] 2016-07-20 11:01
https://github.com/doctrine/DoctrineORMModule/pull/479

**Comment by webimpress** [comment] 2016-07-20 11:01
`DoctrineORMModule` is not yet fully compatible with ZF3 (`zend-mvc` v3), only with `zend-servicemanager` v3. Please have a look on #479.

To me [release 1.0.0](https://github.com/doctrine/DoctrineORMModule/releases/tag/1.0.0) has wrong and confusing description:
> It is compatible with ZF2 and ZF3

It is __not__ compatible with ZF3 !

**Comment by gulijiyag** [comment] 2016-07-20 11:06
@webimpress Sorry for my ignorance, how to install that? It's a pull request, not merged yet, right? Thank you in advance.

**Comment by webimpress** [comment] 2016-07-20 11:17
@gulijiyag yes, it's not merged yet.

If you want to test this PR with your new application you can add to your `composer.json`:
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/webimpress/DoctrineModule.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/webimpress/DoctrineORMModule.git"
        }
    ],
```

and in `require` section of `composer.json`:
```
        "doctrine/doctrine-module": "dev-feature/zf3-support",
        "doctrine/doctrine-orm-module": "dev-feature/zf3-support"
```

Please notice this is __dev__ version, it could be completely changed. It's required also https://github.com/doctrine/DoctrineModule/pull/564.

It's highly __not__ recommended to use it with production applications.

@gianarb @Ocramius what is the release plan of DoctrineModule and DoctrineORMModule for ZF3?

**Comment by gulijiyag** [comment] 2016-07-20 11:22
Yes, I think I will rollback to ZF2 in my project and create a new project just to test ZF3 with your pull request.
That has been a lot of work. Really good job. Keep it up.

**Comment by olegkrivtsov** [comment] 2016-07-22 10:53
When will you support ZF3?

**Comment by gulijiyag** [comment] 2016-07-22 14:23
I think that @gianarb @Ocramius can answer that.

**Comment by heiglandreas** [comment] 2016-07-22 15:36
@olegkrivtsov Have you tried https://github.com/DASPRiD/container-interop-doctrine as described in [this blogpost by @asgrim](https://www.jamestitcumb.com/posts/integrating-doctrine-expressive-easier)? It's not ZF3 but in combination with https://packagist.org/packages/phly/zend-servicemanager-interop it might work...

**Comment by thoys** [comment] 2016-08-01 13:17
Seems to be supported now :) https://github.com/doctrine/DoctrineORMModule/pull/493

**Comment by webimpress** [comment] 2016-08-01 15:05
It is, but not released yet. Please be careful with using `dev-master` !

**Comment by thoys** [comment] 2016-08-01 15:16
living on the edge! :smile:

**Comment by gianarb** [comment] 2016-08-01 17:31
Yes I decided to merge this PR in order to grab feedback and work to make a stable release soon.. Right now dev-master is unstable and unreleased :)

**Comment by olegkrivtsov** [comment] 2016-08-10 11:50
When do you plan to release the new version of `doctrine/doctrine-orm-module` package?

**Comment by viyirenov** [comment] 2016-08-10 18:56
@olegkrivtsov +1

**Comment by Arkadiusz234** [comment] 2016-08-10 21:18
@olegkrivtsov +1

**Comment by alissondeveloper** [comment] 2016-08-11 12:34
When the doctrine is compatible with the ZF3??

it's hard to work with Zend Db!!!

**Comment by kokspflanze** [comment] 2016-08-11 15:02
@alissondeveloper you can add in your composer.json this, until its not released

```code
"doctrine/doctrine-orm-module": "dev-master as 1.0.9",
"doctrine/doctrine-module": "dev-master",
```

**Comment by alissondeveloper** [comment] 2016-08-11 16:38
@kokspflanze Thank you friend, I use the dev for now ...

**Comment by devtosystems** [comment] 2016-08-16 21:52
Until this moment:

```bash
~$ composer require doctrine/doctrine-orm-module
Using version ^1.0 for doctrine/doctrine-orm-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-orm-module ^1.0 -> satisfiable by doctrine/doctrine-orm-module[1.0.0].
    - doctrine/doctrine-orm-module 1.0.0 requires zendframework/zend-mvc ^2.5.2 -> satisfiable by zendframework/zend-mvc[2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.1, 2.7.10, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9] but these conflict with your requirements or minimum-stability.
```

But I'm using dev-master for a while.

**Comment by webimpress** [comment] 2016-08-16 22:07
@devtosystems Do you have enabled `Zend\Form` module?

**Comment by devtosystems** [comment] 2016-08-16 22:25
Yes and setted in `config/modules.config.php` file

**Comment by webimpress** [comment] 2016-08-17 13:14
@devtosystems I've just tried to build ZF3 application with Doctine:
https://github.com/webimpress/zf3-doctrine
All seems to be fine. Let me know if you still have some issues - definitely then I need more information about your modules/configuration etc, base configuration works.

**Comment by sathyashrayan** [comment] 2016-08-23 07:24
I get this error when I try command line "./doctrine-module -help"

PHP Fatal error:  Uncaught Zend\ModuleManager\Exception\MissingDependencyModuleException: Module "DoctrineORMModule" depends on module "DoctrineModule", which was not initialized before it in /var/www/html/__/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php:40
Stack trace:
#0 /var/www/html/__/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\ModuleManager\Listener\ModuleDependencyCheckerListener->__invoke(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/www/html/__/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#2 /var/www/html/__/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(181): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/www/html/__/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule(Object(DoctrineORMModule\Mo in /var/www/html/__/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php on line 40

Fatal error: Uncaught Zend\ModuleManager\Exception\MissingDependencyModuleException: Module "DoctrineORMModule" depends on module "DoctrineModule", which was not initialized before it in /var/www/html/__/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php:40
Stack trace:
#0 /var/www/html/__/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\ModuleManager\Listener\ModuleDependencyCheckerListener->__invoke(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/www/html/__/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#2 /var/www/html/__/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(181): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/www/html/__/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule(Object(DoctrineORMModule\Mo in /var/www/html/__/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php on line 40

**Comment by kokspflanze** [comment] 2016-08-23 08:36
did you add `DoctrineModule` in your `application.config.php` ?

like at https://github.com/doctrine/DoctrineORMModule#installation written

**Comment by sathyashrayan** [comment] 2016-08-23 09:20
Hi kokspflanze,
   Thanks for your reply..

  Yes I did give when its asked during installation. The problem was that the entries in application's module.config.php is stored in reverse order during installation (zf3). So I need to manually change it in the config array.
  
  But now I am facing a new issue in command line 
  
  ./vendor/bin/doctrine-module -help
  
  is throwing this error
  
  PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES) in /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'username', 'password', Array)
#1 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'username', 'password', Array)
#2 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'username', 'password', Array)
#3 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#5 /var/www/ht in /var/www/html/__/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 754

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES) in /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'username', 'password', Array)
#1 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'username', 'password', Array)
#2 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'username', 'password', Array)
#3 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /var/www/html/__/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#5 /var/www/ht in /var/www/html/__/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 754

My module config is

1)[site path]/config/autoload/global.php

 'doctrine' => [
        'connection' => [
            // default connection name
            'orm_default' => [
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host'     => 'localhost',
                    'port'     => '3306',
                    'user'     => 'root',
                    'password' => '',
                    'dbname'   => 'db',
                ]
            ]
        ]
    ],
    
    2)module/module_name/config/module.config.php
    
       'doctrine' => [
        
        'driver' => [
            'Doctrine_driver' => [
                'class' => AnnotationDriver::class,
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../../module/Test/src/Entity',
                ],
            ],
            'orm_default' => [
                'drivers' => [
                    'Test\\Entity' => 'Doctrine_driver',
                ],
            ],
        ],
    ],
    
I am not sure if the issue is from my config or from module..

**Comment by gianarb** [comment] 2016-08-23 09:58
Please check in your `application.config.php` if you add both modules..
`DoctrineModule` and `DoctrineORMModule` 

Thanks a lot!

**Comment by sathyashrayan** [comment] 2016-08-23 10:46
@gianarb Yes. I did added the entry of both in [site path]/config/module.config.php as I use zf3 and the application config is in module.config.php

**Comment by kokspflanze** [comment] 2016-08-23 11:08
@sathyashrayan looks like your config is wrong, db username/password

`
Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES)`

**Comment by sathyashrayan** [comment] 2016-08-23 14:18
@kokspflanze  thanks for your reply. But the same configuration parameter works for database access with 'db'.

**Comment by gianarb** [comment] 2016-08-23 14:25
@sathyashrayan are you trying to connect to mysql from the same local machine/server/vm?
Because it seems really a problem of connection. If your code is running inside a VM you need to check your from inside your VM.

Thanks

**Comment by sathyashrayan** [comment] 2016-08-23 15:18
@gianarb Thanks for your reply..

I wanted to double check. So I installed a fresh zf3. My system is a personal laptop

My system configuration
--
Ubundu 16.4.1 LTS
php 7
Apache/2.4.18 (Ubuntu) 
Mysql 5
host: localhost

First I gave this command as per in-depth guide

composer create-project -s dev zendframework/skeleton-application .

It asked me several questions according to the in-depth guide. I gave all yes and developer tools configuration in application's another configuration file.

The I changed the composer.json as per above instruction and "composer update".

It asked some questions and The installation went well. When I gave the command in CLI ./vendor/bin/doctrine-module -help
I got a dependency issue. So I need to interchange the order of module array in module.config.php application. The DoctrineModule should come first but the automatic configuration process is storing the DoctrineModule after DoctrineORMModule.

Now I change the [site path]/config/autoload/global.php with the correct database configuration. I still get the error as wrong credentials. I have not created any vhost yet. How come the correct credentials does not work in doctroin? I have used the same config for database access with table gateway and it works.

May be I am missing something basic?

**Comment by webimpress** [comment] 2016-08-23 15:58
@sathyashrayan I've notice the wrong order on module list before. I will test it today, and will try to find solution for it.
This is only one issue? Is it working fine when you change the order?

**Comment by sathyashrayan** [comment] 2016-08-23 16:14
@webimpress Thanks for the concern. If you could test the command line migration tool then that will be fine too. Please take my system env into consideration.

**Comment by webimpress** [comment] 2016-08-23 18:46
@sathyashrayan I think I know why you got the same wrong credentials error - `doctrine-module` script always uses cached configuration, I think it could be done better in this script.

If you remove cached configuration in `data/cache` and try again all should be fine.

You can have a look on my base skeleton [ZF3 + Doctrine](https://github.com/webimpress/zf3-doctrine). All is good there. Command line tools works :)

My installation process was:
```bash
composer create-project -s dev zendframework/skeleton-application zf3-doctrine
cd zf3-doctrine
composer update
composer require doctrine/doctrine-orm-module:dev-master
# swap `DoctrineModule` and `DoctrineORMModule` in `modules.config.php`
# add doctrine configuration
```

Let me know if it works now for you.

**Comment by webimpress** [comment] 2016-08-23 19:17
There could be one more issue with ZF3 - please check if you have installed `zendframework/zend-mvc-console` and enabled module `Zend\Mvc\Console`. It's required to use command line tools on ZF3, and it is in `suggest` section in `composer.json` of `DoctrineModule`

**Comment by sathyashrayan** [comment] 2016-08-24 04:59
@webimpress 

Thanks a lot for the guide. Yes, when I delete the data/cache files the command line is perfectly working with 

./vendor/bin/doctrine-module -help

But I have not tested all the process such as migration and record fetch with orm

I will explain my process so that it's useful for others

My system configuration
-
Ubundu 16.4.1 LTS
php 7
Apache/2.4.18 (Ubuntu) 
Mysql 5
host: localhost

1)Install zf3 skeleton with https://docs.zendframework.com/tutorials/getting-started/skeleton-application/. Its better say yes to all the module including developer tools and Zend\Mvc\Console.  

2)Delete all the files in [site path]/data/cache/* Since we will be installing the zend/cache also the configuration will be stored in the cache files. Without this the command line tool such as ./vendor/bin/doctrine-module -help does not works.

3)Add the following in the [site path]/composer.json. 

 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/webimpress/DoctrineModule.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/webimpress/DoctrineORMModule.git"
        }
    ],
    
and in require section of composer.json:

"doctrine/doctrine-module": "dev-feature/zf3-support",
"doctrine/doctrine-orm-module": "dev-feature/zf3-support"    

We could also add through command line 

composer require doctrine/doctrine-orm-module:dev-master

but there is a error called "Missing view helper "zendDeveloperToolsTime" This is because of lowercase issue of "Z" as explained in this bugs

https://github.com/doctrine/DoctrineORMModule/pull/496
https://github.com/doctrine/DoctrineORMModule/pull/496/commits/ff885692ca9cc0fce09a64a6208ae7afba283717

4)Now give the command as “composer update”. It will ask some questions about installing zend/paginator, `DoctrineModule` and `DoctrineORMModule`. Say yes for all and keep the configuration in [site path]/config/modules.config.php by entering 1 in the option.

5)After this you need to swap the order of `DoctrineModule` and `DoctrineORMModule` in [site path]/config/modules.config.php or else it will throws error for dependency.

5)Now add the database configuration in [site path]/config/autoload/*.php (either in global.php or local.php. For deciding please cross check the advanced configuration session of docs https://docs.zendframework.com/tutorials/advanced-config/ The config is 

'doctrine' => [
        'connection' => [
            'orm_default' => [
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host'     => 'your host (localhost)',
                    'port'     => 'your port',
                    'user'     => 'your user name',
                    'password' => 'your password',
                    'dbname'   => 'your database',
                ]
            ]
        ]
    ],

I use mysql so the driver class points to PDO. For your database engine it might change accordingly

6)Now create a directory named Entity in your module such as [site path]/module/your module name/src/Entity

7)Add the following module level config in [site path]/module/your module name/config/module.config.php

use Doctrine\ORM\Mapping\Driver\AnnotationDriver;
use Doctrine\DBAL\Driver\PDOSqlite\Driver;

[other config array such as route,views, service ect]

'doctrine' => [
        'driver' => [  
            __NAMESPACE__ . '_driver' => [
                'class' => AnnotationDriver::class,
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../src/Entity'
                ],
            ],
            'orm_default'             => [
                'drivers' => [
                    __NAMESPACE__ => __NAMESPACE__ . '_driver'
                ]
            ]
        ]
    ] 


Hope this will help anyone who wants to install and test DoctrinORM with zf3.

**Comment by MatthiasKuehneEllerhold** [comment] 2016-08-24 06:13
Instead of using the (deprecated) zend-console you could just use the doctrine-module binary in your vendor/bin directory.

**Comment by webimpress** [comment] 2016-08-24 11:15
@sathyashrayan Please use `dev-master` from doctrine (for `DoctrineModule` and `DoctrineORMModule` modules) instead of `zf3-support` from my repositories. It's a bit different right now. Of course please remember it is not stable version yet so it's not recommended to use it on production environment!

**Comment by viyirenov** [comment] 2016-08-24 16:53
@webimpress - Can you tell me the process to install ZF3 apigility skeleton + doctrine?

**Comment by webimpress** [comment] 2016-08-24 22:03
@viyirenov Please have a look on my example repository ZF3 + Apigility + Doctrine:
https://github.com/webimpress/zf3-apigility-doctrine

**The installation process is as following:**

**1.** Install Apigility (v1.4) - you can clone repository [`zf-apigility-skeleton`](https://github.com/zfcampus/zf-apigility-skeleton), use [apigility installer](https://apigility.org/documentation/intro/installation#from-the-terminal) or use [`composer create-project`](https://apigility.org/documentation/intro/installation#via-composer-create-project).

**2.** Add doctrine configuration:
**a)** modify `composer.json` - add new section:
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/webimpress/zf-apigility-doctrine"
        },
        {
            "type": "vcs",
            "url": "https://github.com/webimpress/zf-doctrine-hydration-module"
        }
    ],
```
(these packages are not yet merged, still in development, **please don't use it on live environment!**).

and in `required`required section add:
```json
        "zfcampus/zf-apigility-doctrine": "dev-feature/zf3compat",
        "doctrine/doctrine-module": "dev-master as 1.1",
        "doctrine/doctrine-orm-module": "dev-master",
        "phpro/zf-doctrine-hydration-module": "dev-feature/zf3compat"
```

**b)** Run `composer update`.
Installer will ask you where to add new modules. Please choose `modules.config.php` for all modules except `ZF\Apigility\Doctrine\Admin` - this module should be added into `development.config.php.dist` (and `development.config.php` if you already have enabled development mode).

**c)** Ensure you have correct order of modules in `modules.config.php` and `development.config.php.dist` (`development.config.php`), you should have:

In `modules.config.php`:
```php
return [
    'DoctrineModule',
    'DoctrineORMModule',
    'Phpro\\DoctrineHydrationModule',
    'ZF\\Apigility\\Doctrine\\Server',
    'Zend\\Cache',
    'Zend\\Form',
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\InputFilter',
    'Zend\\Paginator',
    'Zend\\Router',
    'Zend\\Validator',
    'ZF\\Apigility',
    'ZF\\Apigility\\Documentation',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\OAuth2',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'Application',
];
```

and in `development.config.php.dist` (`development.config.php`):
```php
return [
    'modules' => [
        'ZendDeveloperTools',
        'ZF\Apigility\Admin',
        'ZF\Apigility\Doctrine\Admin',
    ],
    // ...
];
```

**d)** Add your doctrine configuration.
Please remember to keep passwords and all sensitive data in local configuration files.

**3.** Enable development mode.
If it was enabled before please disable it and enable again.


**Attention!**
--------------
All doctrine modules are not yet released. Please use it on your own responsibility. It is highly unrecommended to use it on production environment.

Reporting all detected issue will be appreciated.

**So far I've noticed following problems:**
- using command line tool `doctrine-module` create cached configuration files and use it in all calls (resolved in https://github.com/doctrine/DoctrineModule/pull/572, not merged yet);
- modules order (in `modules.config.php`) installed with `zend-component-installer`;
- generating entities in PSR-4 module (entities are created in wrong directory).

**Comment by DennisDobslaf** [comment] 2016-08-30 10:59
I'm not sure if this should be another issue, because of the little off-topic discusion above.
But I give it a try:

I'm using the module [slm/queue-doctrine](https://github.com/juriansluiman/SlmQueueDoctrine/) wich tries to load ^1.0 of doctrine-orm-module. composer update runs into a not-satisfiable problem in this combination. Don't know how to fix this. I don't want to fork everything.

**Comment by webimpress** [comment] 2016-08-30 11:14
@DennisDobslaf DoctrineORMModule is not yet released with ZF3 support. It is merged to master branch, but it is not tagged. You can use `dev-master as 1.1` but please remember it is not recommended to use on production environment.

**Comment by olegkrivtsov** [comment] 2016-08-31 12:35
How do I run Doctrine migrations console commands in ZF3? Previously, in ZF2, I could do the following:

`php index.php migrations:migrate`

How is the accomplished now (in ZF3)?

**Comment by Estigy** [comment] 2016-11-17 13:36
Do you have any news for us on this?
ZF3 has been around now for quite a couple of months.

**Comment by MatthiasKuehneEllerhold** [comment] 2016-11-17 13:38
@olegkrivtsov use `vendor/bin/doctrine-module migrations:migrate` instead (its usable for all doctrine CLI commands)

**Comment by MatthiasKuehneEllerhold** [comment] 2016-11-17 13:41
@Estigy This composer.json works for me:
```json
{
    ... 
    "require": {
        "doctrine/doctrine-orm-module": "^1.1",
        "zendframework/zend-mvc": "^3.0.2"
    }
    ...
}
```

**Comment by bluebaroncanada** [comment] 2017-02-18 10:59
This error leads here from Google even though this isn't for this error.

PHP Fatal error:  Uncaught Zend\ModuleManager\Exception\MissingDependencyModuleException: Module "DoctrineORMModule" depends on module "DoctrineModule", which was not initialized before it in /var/www/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php:40
Stack trace:
#0 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\Listener\ModuleDependencyCheckerListener->__invoke(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#2 /var/www/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(181): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/www/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule(Object(DoctrineORMModule\Module))
#4 /var/www/vendor/zendframework/zend-eventmanager/src/Eve in /var/www/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php on line 40

Fatal error: Uncaught Zend\ModuleManager\Exception\MissingDependencyModuleException: Module "DoctrineORMModule" depends on module "DoctrineModule", which was not initialized before it in /var/www/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php:40
Stack trace:
#0 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\Listener\ModuleDependencyCheckerListener->__invoke(Object(Zend\ModuleManager\ModuleEvent))
#1 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#2 /var/www/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(181): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent))
#3 /var/www/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule(Object(DoctrineORMModule\Module))
#4 /var/www/vendor/zendframework/zend-eventmanager/src/Eve in /var/www/vendor/zendframework/zend-modulemanager/src/Listener/ModuleDependencyCheckerListener.php on line 40

The solution is to flip:

    'DoctrineORMModule',
    'DoctrineModule',

to

    'DoctrineModule',
    'DoctrineORMModule',

This is currently an issue ... right now.  Fresh install with the skeleton.

**Comment by webimpress** [comment] 2017-02-18 11:34
@bluebaroncanada The problem is resolved with zend-component-installer 0.4. The current version is 0.6 and with this version all should be fine. If you are using version from current ZendSkeletonApplication there is still version 0.3, but you can safely update it to the latest one, and then issue described above should be resolved.

**Comment by Ocramius** [comment] 2017-02-18 11:35
That's not an issue, that's an intentional failure telling you that you
messed up the order.

**Comment by webimpress** [comment] 2017-02-18 11:38
@Ocramius if you are using zend-component-installer <0.4 it is the issue, because DoctrineModule and DoctrineORMModule are installed __in wrong order__. As I mentioned, with zend-component-installer all is fine, and requiring doctrine modules will install them in correct order in the module list in the configuration.

**Comment by bluebaroncanada** [comment] 2017-02-18 11:56
@webimpress Thanks!

**Closed** 2017-06-05 03:38 UTC
