### ISSUE TITLE
new tag

### ISSUE THREAD

**Issue by Perfect-Web** [doctrine/DoctrineORMModule#402] opened 2015-05-01 11:17 UTC
guys pls can we have a tag `0.9.x` whatever from the master ? cause right now there are alot of dependencies broken and i can't fix them because the features i require are in `dev-master` and they require `0.*`

Thanks

**Comment by Ocramius** [comment] 2015-05-01 12:49
Dupe of #400

**Closed by Ocramius** 2015-05-01 12:49 UTC
