### ISSUE TITLE
Cache. Incomplete object

### ISSUE THREAD

**Issue by marinovdf** [doctrine/DoctrineORMModule#474] opened 2016-06-29 13:32 UTC
Hi.
I use Redis storage for cache of my application.
Now I working with cache like this:
```
$cacheKey = 'Entity.id.'.$id;
if ($cache->contains($cacheKey)) {
    $entity = $cache->fetch($cacheKey);    // entity from cache
} else {
    $entity = $this->getEntityManager()->find(Entity::class, $id);
    $cache->save($cacheKey, $entity);
}
```
Data successfully pushed in the Redis.
But when I get entity from cache and working with it, I get an error 
`The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition 'DoctrineORMModule\Proxy\__CG__\SomeModule\Entity\Entity'`

What am I doing wrong? Thanks.

**Comment by Ocramius** [comment] 2016-06-30 11:41
Few things here:

 * don't store objects in the cache
 * **don't** store objects in the cache
 * **DON'T** store objects in the cache
 * Proxies are not autoloaded by default: you may set up your own autoloader to do so (this is expected)
 * It is very risky to store proxies in cache, since proxies depend on the ORM to trigger lazy-loading. Trying to access any association on a de-serialized proxy will cause a lot of issues
 * Before you ask: no, you cannot know if the ORM will return a proxy or a real instance, and you can't convert a proxy to a real instance

Hope that helps :-)

Closing, as this is not a bug, but expected behavior.

**Closed by Ocramius** 2016-06-30 11:41 UTC

**Comment by marinovdf** [comment] 2016-07-05 06:31
Thanks. You helped me
