### ISSUE TITLE
ZF2 Console Route error when loading DoctrineORMModule

### ISSUE THREAD

**Issue by 3m0** [doctrine/DoctrineORMModule#330] opened 2014-05-13 02:15 UTC
Whenever I setup a console route, when I run it I get an error related to the default connection to the database, even if my action does not use a database connection at all. If I run the same action from outside the console, everything runs fine, the problem only occurs when the route is run from console. An excerpt from the stack trace (the last part) can be found here:

http://pastebin.com/Dmg8g9Sv

I'm using Zend Framework 2.3 with Doctrine ORM Module 0.8.0.
I've also noticed that when I comment line 63 from the file doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php like this:

//$events->getSharedManager()->attach('doctrine', 'loadCli.post', array($this, 'initializeConsole'));

The problem doesn't occur and everything seems to work.

**Comment by gianarb** [comment] 2015-04-09 11:08
I close this issue.
If this problem persist write here and i reopen

Thanks!

**Comment by mdjaman** [comment] 2016-03-30 11:23
Please open it!
Here my composer dependancy:

```
"require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.3.*",
        "sp/jms-serializer-module": "dev-master",
        "doctrine/doctrine-orm-module": "0.10.*",
        "gedmo/doctrine-extensions": "dev-master",
    },
```
Got : 
Zend\ServiceManager\Exception\ServiceNotCreatedException: An exception was raised while creating "doctrine.cli"; no instance returned

**Comment by gianarb** [comment] 2016-03-30 12:06
Hello can you share your composer info?
Thanks

**Comment by mdjaman** [comment] 2016-03-30 12:44
i would send the error log if know how to log it since i use git bash prompt :(

**Comment by mdjaman** [comment] 2016-03-30 12:49
My bad about previous message. Log from php_error file.
Thanks

> [30-Mar-2016 14:40:47 Europe/Paris] PHP Warning:  array_map(): An error occurred while invoking the map callback in C:\wamp\www\inventory\vendor\doctrine\doctrine-orm-module\src\DoctrineORMModule\Module.php on line 137
> [30-Mar-2016 14:40:47 Europe/Paris] PHP Stack trace:
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   1. {main}() C:\wamp\www\inventory\vendor\doctrine\doctrine-module\bin\doctrine-module:0
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   2. include() C:\wamp\www\inventory\vendor\doctrine\doctrine-module\bin\doctrine-module:4
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   3. Zend\Mvc\Application::init() C:\wamp\www\inventory\vendor\doctrine\doctrine-module\bin\doctrine-module.php:53
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   4. Zend\Mvc\Application->bootstrap() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php:260
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   5. Zend\ServiceManager\ServiceManager->get() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php:153
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   6. Zend\ServiceManager\ServiceManager->create() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:525
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   7. Zend\ServiceManager\ServiceManager->doCreate() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:593
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   8. Zend\ServiceManager\ServiceManager->createFromFactory() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:633
> [30-Mar-2016 14:40:47 Europe/Paris] PHP   9. Zend\ServiceManager\ServiceManager->createServiceViaCallback() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:1055
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  10. call_user_func:{C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923}() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  11. Zend\Mvc\Service\RouterFactory->createService() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  12. call_user_func:{C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Service\RouterFactory.php:60}() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Service\RouterFactory.php:60
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  13. Zend\Mvc\Router\SimpleRouteStack::factory() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Service\RouterFactory.php:60
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  14. Zend\Mvc\Router\SimpleRouteStack->addRoutes() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Router\SimpleRouteStack.php:84
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  15. Zend\Mvc\Router\Console\SimpleRouteStack->addRoute() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Router\SimpleRouteStack.php:140
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  16. Zend\Mvc\Router\Console\SimpleRouteStack->routeFromArray() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Router\Console\SimpleRouteStack.php:51
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  17. Zend\Mvc\Router\SimpleRouteStack->routeFromArray() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Router\Console\SimpleRouteStack.php:80
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  18. Zend\ServiceManager\AbstractPluginManager->get() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\Mvc\Router\SimpleRouteStack.php:274
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  19. Zend\ServiceManager\ServiceManager->get() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\AbstractPluginManager.php:103
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  20. Zend\ServiceManager\ServiceManager->create() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:525
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  21. Zend\ServiceManager\ServiceManager->doCreate() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:593
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  22. Zend\ServiceManager\AbstractPluginManager->createFromFactory() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:633
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  23. Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\AbstractPluginManager.php:215
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  24. Zend\ServiceManager\ServiceManager->createServiceViaCallback() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\AbstractPluginManager.php:259
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  25. call_user_func:{C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923}() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  26. DoctrineModule\Service\SymfonyCliRouteFactory->createService() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  27. Zend\ServiceManager\ServiceManager->get() C:\wamp\www\inventory\vendor\doctrine\doctrine-module\src\DoctrineModule\Service\SymfonyCliRouteFactory.php:38
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  28. Zend\ServiceManager\ServiceManager->create() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:525
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  29. Zend\ServiceManager\ServiceManager->doCreate() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:593
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  30. Zend\ServiceManager\ServiceManager->createFromFactory() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:633
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  31. Zend\ServiceManager\ServiceManager->createServiceViaCallback() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:1055
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  32. call_user_func:{C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923}() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  33. DoctrineModule\Service\CliFactory->createService() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:923
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  34. Zend\EventManager\EventManager->trigger() C:\wamp\www\inventory\vendor\doctrine\doctrine-module\src\DoctrineModule\Service\CliFactory.php:85
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  35. Zend\EventManager\EventManager->triggerListeners() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php:207
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  36. call_user_func:{C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php:468}() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php:468
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  37. DoctrineORMModule\Module->initializeConsole() C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php:468
> [30-Mar-2016 14:40:47 Europe/Paris] PHP  38. array_map() C:\wamp\www\inventory\vendor\doctrine\doctrine-orm-module\src\DoctrineORMModule\Module.php:137
> [30-Mar-2016 14:40:47 Europe/Paris] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES)' in C:\wamp\www\inventory\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43
> Stack trace:
> #0 C:\wamp\www\inventory\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'username', 'password', Array)
> #1 C:\wamp\www\inventory\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'username', 'password', Array)
> #2 C:\wamp\www\inventory\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'username', 'password', Array)
> #3 C:\wamp\www\inventory\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(429): Doctrine\DBAL\Connection->connect()
> #4 C:\wamp\www\inventory\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatfo in C:\wamp\www\inventory\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php on line 930

**Comment by gianarb** [comment] 2016-03-30 12:52
Thanks but enter into the project's root and run 
`composer info` and copy here your installed dependencies, thanks

**Comment by mdjaman** [comment] 2016-03-30 12:59
Ok here the installed section

> installed:
>   behat/transliterator                      v1.1.0
>   bjyoungblood/bjy-authorize                dev-master 87e10da
>   bjyoungblood/bjy-profiler                 dev-master 1d05f9b
>   danielss89/zfc-user-admin                 dev-master 16bd258
>   doctrine/annotations                      v1.2.7
>   doctrine/cache                            v1.6.0
>   doctrine/collections                      v1.3.0
>   doctrine/common                           v2.6.1
>   doctrine/data-fixtures                    dev-master b4213c2
>   doctrine/dbal                             v2.5.4
>   doctrine/doctrine-module                  1.0.1
>   doctrine/doctrine-orm-module              0.10.0
>   doctrine/inflector                        v1.1.0
>   doctrine/instantiator                     1.0.5
>   doctrine/lexer                            v1.0.1
>   doctrine/migrations                       dev-master 5f9429e
>   doctrine/orm                              v2.5.4
>   evandotpro/edp-superluminal               dev-master 59e8b98
>   gedmo/doctrine-extensions                 dev-master 8eae090
>   goalio/goalio-forgotpassword              1.0.2
>   goalio/goalio-forgotpassword-doctrine-orm dev-master 8894334
>   goalio/goalio-mailservice                 1.2.1
>   imagine/imagine                           dev-master 10e9522
>   jms/metadata                              1.5.1
>   jms/parser-lib                            1.0.0
>   jms/serializer                            0.16.0
>   mdjaman/mdjaman-common                    dev-master 93ed230
>   ocramius/ocra-cached-view-resolver        dev-master 22f08af
>   ocramius/proxy-manager                    1.0.2
>   phpcollection/phpcollection               0.4.0
>   phpdocumentor/reflection-docblock         2.0.4
>   phpoption/phpoption                       1.5.0
>   phpspec/prophecy                          v1.6.0
>   phpunit/php-code-coverage                 2.2.4
>   phpunit/php-file-iterator                 1.4.1
>   phpunit/php-text-template                 1.2.1
>   phpunit/php-timer                         1.0.7
>   phpunit/php-token-stream                  1.4.8
>   phpunit/phpunit                           4.8.24
>   phpunit/phpunit-mock-objects              2.3.8
>   san/san-session-toolbar                   dev-master 4eb5471
>   sebastian/comparator                      1.2.0
>   sebastian/diff                            1.4.1
>   sebastian/environment                     1.3.5
>   sebastian/exporter                        1.2.1
>   sebastian/global-state                    1.1.1
>   sebastian/recursion-context               1.0.2
>   sebastian/version                         1.0.6
>   sp/jms-serializer-module                  dev-master d1c187d
>   symfony/console                           v3.0.3
>   symfony/polyfill-mbstring                 v1.1.1
>   symfony/yaml                              v3.0.3
>   zendframework/zend-developer-tools        dev-master b2509f8
>   zendframework/zenddiagnostics             v1.0.8
>   zendframework/zendframework               2.3.9
>   zendframework/zendxml                     1.0.2
>   zendframework/zftool                      dev-master 840c3ee
>   zf-commons/zfc-admin                      dev-master 86794b7
>   zf-commons/zfc-base                       v0.1.2
>   zf-commons/zfc-user                       1.4.2
>   zf-commons/zfc-user-doctrine-orm          dev-master 252d77f

**Comment by Ocramius** [comment] 2016-03-30 18:46
```
 > 
> [30-Mar-2016 14:40:47 Europe/Paris] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES)'
```

This bug is likely related to https://github.com/doctrine/DoctrineBundle/issues/351#issuecomment-65771528

The problem is following:

 1. CLI commands are requested to the ServiceManager
 2. one or more CLI commands depend on the EntityManager, which is requested to the ServiceManager
 3. the EntityManager is requested to the ServiceManager
 4. the EntityManager is instantiated
 5. the EntityManager initializes the DBAL platform (required) using [`Connection#getDatabasePlatform()`](https://github.com/doctrine/dbal/blob/61e1f860a304c3fb6961ecbec36927b5f20b71c6/lib/Doctrine/DBAL/Connection.php#L325)
 6. if no `serverVersion` connection parameter is provided, a [connection is attempted while detecting the database platform](https://github.com/doctrine/dbal/blob/61e1f860a304c3fb6961ecbec36927b5f20b71c6/lib/Doctrine/DBAL/Connection.php#L413-L439)

This cannot be worked around by us, as MySQL keeps breaking compatibility in minor versions. You have to specify the `'serverVersion'` in the configuration if you want the connection to be lazily initialized on demand, and not at ORM instantiation time.

@gianarb I think this is a documentation task.

**Comment by TomHAnderson** [comment] 2017-06-05 03:57
What's the documentation status of this?

**Comment by TomHAnderson** [comment] 2017-09-20 01:51
Closed due to lack of activity.

**Comment by TomHAnderson** [comment] 2017-09-21 02:27
@gianarb you postulated a doc leak, @Ocramius you explained it,
so, is this something we need to include in the documentation?

**Comment by thomasvargiu** [comment] 2017-09-22 09:02
That's why I created PR #534. Setting `server_version` is not enough to use a a lazy connection with the current version of Doctrine. It's necessary to set the platform for what I remember.

**Comment by TomHAnderson** [comment] 2017-11-13 09:46
PR #534 has been merged so I'm closing this ticket.

**Closed by TomHAnderson** 2017-11-13 09:46 UTC
Labels: docs
