### ISSUE TITLE
Missing params on Insert

### ISSUE THREAD

**Issue by SilverioMiranda** [doctrine/DoctrineORMModule#576] opened 2018-08-28 08:43 UTC
How i suppose debug this error :
![image](https://user-images.githubusercontent.com/1939153/44711528-f2295480-aa84-11e8-9e9c-2e68cf589041.png)

Using SQLite in memory
Doctrine version : "doctrine/doctrine-orm-module":"^2.1.2",
VeiculoMarca file : 
```
<?php
namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * This class represents a registered user.
 * @ORM\Entity()
 * @ORM\Table(name="veiculo_marca")
 */
class VeiculoMarca
{

     /**
     * @ORM\Id
     * @ORM\Column(name="Id",type="integer", nullable=false, options={"autoincrement":true})
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $Id;

    /**
     * @ORM\Column(name="Nome")
     */
    protected $Nome;

    public function getId()
    {
        return $this->Id;
    }
    public function getNome()
    {
        return $this->Nome;
    }
    public function setId($Id)
    {
        $this->Id = $Id;
    }
    public function setNome($Nome)
    {
        $this->Nome = $Nome;
    }
}
```

**Comment by Ocramius** [comment] 2018-08-28 11:40
Closing here: this is not a bug nor an issue with the module. From what I can read, you are attempting to insert with one bound parameter instead of 2: possibly a mapping issue, but I'd start from reducing your test scenario to just the code location that failed in your project.

**Closed by Ocramius** 2018-08-28 11:40 UTC

**Comment by SilverioMiranda** [comment] 2018-08-28 16:07
Yeah, but i have 2 problems : 
1. This code works with MySql
2. This problem started after i update doctrine to newest version

Thats why im freaking out here

**Comment by Ocramius** [comment] 2018-08-28 22:03
Try to distill it to a test case in DBAL please: we cann fix it once we have something a bit more isolated and clear.

The aim is writing a self-contained test that runs on sqlite and fails on mysql.
