### ISSUE TITLE
Calling `vendor/bin/doctrine-module orm:validate-schema --skip-sync` still connects to DB

### ISSUE THREAD

**Issue by Mezzle** [doctrine/DoctrineORMModule#386] opened 2015-02-25 18:16 UTC
When calling validate schema, but skipping the sync (for CI purposes), the code still tries to connect to the database.

```
+ vendor/bin/doctrine-module orm:validate-schema -n --skip-sync
PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 135

Warning: array_map(): An error occurred while invoking the map callback in /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/doctrine-orm-module/src/DoctrineORMModule/Module.php on line 135
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'username', 'password', Array)
#1 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'username', 'password', Array)
#2 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(358): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'username', 'password', Array)
#3 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBA in /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 909

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'username', 'password', Array)
#1 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'username', 'password', Array)
#2 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(358): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'username', 'password', Array)
#3 /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/doctrine/dbal/lib/Doctrine/DBA in /var/lib/jenkins/jobs/p42-schema-315139603fb1/workspace/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 909
Build step 'Execute shell' marked build as failure
```

**Comment by Ocramius** [comment] 2015-02-25 18:18
Seems like a broken mysql installation to me.

**Comment by Mezzle** [comment] 2015-02-25 19:18
There is no mysql installation on that machine.  Nothing should ever try and connect to mysql on that machine.

The issue is that even though I'm telling it to run with `--skip-sync` (purely check the schema, not the DB), it still tries to connect.

I'm trying to automate this so that if there are changes made to the schema that don't make sense (missing the inverse side of a relationship, for example), then they're flagged up.  I don't want/need to connect to mysql to do this.

**Comment by Ocramius** [comment] 2015-02-25 19:41
Seems like a duplicate of doctrine/DoctrineBundle#351, can you confirm?

**Comment by Mezzle** [comment] 2015-02-25 23:27
No, it's not a duplicate of that.

If I'm not calling something that's going to require connecting to a DB, of any kind, then the DB connection call shouldn't be made.

**Comment by Mezzle** [comment] 2015-02-25 23:32
Basically, in Module.php, when adding the commands to the `\Symfony\Component\Console\Application` - one of the commands is initializing a DB connection.  It shouldn't initiate a DB connection unless that specific command is called.

**Comment by Ocramius** [comment] 2015-02-26 10:20
@Mezzle  any call to `getPlatform` anywhere (for example in the metadata factory) does that.

**Comment by Mezzle** [comment] 2015-02-27 11:29
@Ocramius That may be the case, but - should it?  If I want to do something (check the schema without sync check) - should it connect to the DB?

**Comment by Ocramius** [comment] 2015-02-27 11:55
No, it shouldn't, but we didn't find a solution for it yet.

**Comment by svycka** [comment] 2015-03-05 13:44
@Ocramius maybe workaround for this? Maybe I could specify server_version somehow? This should prevent from connecting database no?

**Comment by Ocramius** [comment] 2015-03-05 13:49
Specifying the version is indeed solving this problem

**Comment by Mezzle** [comment] 2015-03-05 13:52
@Ocramius is that something I need to do (workaround) - or something that needs to be done in doctrine?

**Comment by Ocramius** [comment] 2015-03-05 13:53
It's a workaround

**Comment by svycka** [comment] 2015-03-05 14:21
How can I specify server_version in this module?

**Comment by gianarb** [comment] 2015-04-16 07:27
Hi @Mezzle this problem persist?

**Comment by svycka** [comment] 2015-04-16 07:39
just tested. yes it still persist.

**Comment by timwsuqld** [comment] 2016-01-13 02:48
How can we use the workaround of specifying the server_version?

**Comment by TomHAnderson** [comment] 2017-06-05 04:30
Closed.  Configuration of server_version is documented at least here: http://symfony.com/doc/current/doctrine/dbal.html

**Closed by TomHAnderson** 2017-06-05 04:30 UTC
Labels: question

**Comment by svycka** [comment] 2017-06-05 05:43
@TomHAnderson I am not sure this solves this issue specifying server version is just a workaround.

**Comment by TomHAnderson** [comment] 2017-06-05 06:00
I agree, @svycka, it's a work-around but I don't see anything to fix if this work-around solves the issue.   

If someone would like to post a PR that would be helpful.

**Comment by svycka** [comment] 2017-06-05 06:04
I also don't know how to fix this but having hard-coded server version in test config is a problem. Maybe someone will find a way to fix this.
