### ISSUE TITLE
Broken CLI routes

### ISSUE THREAD

**Issue by danmarinescu79** [doctrine/DoctrineORMModule#559] opened 2018-03-27 13:36 UTC
Using latest Zend Framework

> "zendframework/zend-servicemanager": "^3.3"

For version **1.1.6** **php public/index.php orm:validate-schema** the output is 

> Reason for failure: Invalid arguments or no arguments provided

while on **1.1.5** output is 

> php public/index.php orm:validate-schema

Mapping
-------

 [OK] The mapping files are correct.

Database
--------

 [OK] The database schema is in sync with the mapping files.
![screen shot 2018-03-27 at 16 34 43](https://user-images.githubusercontent.com/4300427/37970726-d8770008-31dc-11e8-9b1f-6077ce7906d5.png)
![screen shot 2018-03-27 at 16 34 55](https://user-images.githubusercontent.com/4300427/37970729-dc471b3c-31dc-11e8-9518-21559bc5a00a.png)

**Comment by Ocramius** [comment] 2018-03-27 13:43
Dupe of https://github.com/doctrine/DoctrineORMModule/issues/558?

**Comment by danmarinescu79** [comment] 2018-03-27 13:48
well i don't receive any errors or exceptions and i have the development mode enabled  also i'm on the latest version of zend framework, but yes i think the root cause is #558

**Comment by TomHAnderson** [comment] 2018-03-27 21:08
Fixed in 1.1.7

**Closed by TomHAnderson** 2018-03-27 21:08 UTC
